### ISSUE TITLE
Wrong bottomness for some particles in particle lists.

### ISSUE THREAD

**Issue by kaisershafi** [chunshen1987/iSS#2]
In iSS_tables/pdg-s95pv1.dat and iSS_tables/pdg-s95pv1.dat, bottomness for the below particles are given as:
Pion(+)  1
Pion(0)  1
Pion(-)   1
rho(+)    2
rho(0)    2
rho(-)     2
omega   3
which are wrong.

**Comment by chunshen1987** [comment]
fixed. Thanks a lot for reporting!
